### PR TITLE
Cooldown trigger for Ammunition 

### PR DESCRIPTION
**Pull request by juh9870**
This PR is aimed at adding Cooldown trigger condition to the "new" ammunition system.

## Motivation:
In mods, there is often a need to make an ammo that does something every X seconds, but currently the only way to implement it is to use recursion, which limits the amount of activations, as well leads to other issues. This PR allows to just specify a Cooldown trigger, and specify interval in Cooldown field, and this trigger will get invoked at a specified interval.

## Side effects
As a side effect of implementing this PR, all triggers of "new" ammunition now support Cooldown field usage, just like SpawnBullet did previously.

## Performance considerations
This PR was made with performance in mind. I tried my best to limit the amount of processing required during combat. Cooldown-triggered actions use a separate system that I called `ITicker`, which leads to less processing than just emitting "OnCooldown" every frame to all actions.

### CODE REVIEW

**Comment by juh9870** [comment]
Example weapons that would become much easier to make and more stable to operate with this PR:

https://youtu.be/dblbV03y830?si=FShDyzD3R0KZV_au

https://youtu.be/on_EmPRDCFs?si=xHTPWQI6qGM5nLm6

**Comment by juh9870** [comment]
I see that with the recent commits Cooldown in spawn bullet trigger was updated. @PavelZinchenko should I try to update my PR to incorporate this, or is my whole implementation not acceptable, and an entirely new approach shall be taken?

**Comment by PavelZinchenko** [comment]
I've just made a SpawnBullet effect cooldown shared between bullet instances created by the same factory. This allows high-fire-rate weapons to produce their spawn effects while maintaining the cooldown period. I don't think other effects need it.

I am currently reviewing your changes.

**Comment by PavelZinchenko** [comment]
That is how I would do it:

Add interface `ICooldown` with `bool TryUpdate()` method. The implementation is already exists - SpawnBulletAction.SpawnCooldown.

Remove cooldown from actions. Add new action:

```
ActionWithCooldown(IAction action, ICooldown cooldown)
{
    public ConditionType Condition => _action.Condition;
    public CollisionEffect Invoke() => _cooldown.TryUpdate() ? _action.Invoke() : CollisionEffect.None;
}
```
Add extension methods:
```
public static class IActionExtensions
{
    public static IAction WithCooldown(this IAction action, ICooldown cooldown) =>
       cooldown == null ? action : new ActionWithCooldown(action, cooldown);
    public static IAction WithCooldown(this IAction action, float seconds) =>
       cooldown <= 0 ? action : new ActionWithCooldown(action, new Cooldown(seconds));
}
```
Instead of tickers, store `OnCooldown` actions in separate list, invoke them in `UpdatePhysics`
In the `BulletFactory` if cooldown is needed write `SomeAction.WithCooldown(value)`

This will be compatible with the shared cooldown for `SpawnBulletAction` I added before

**Comment by juh9870** [comment]
Thanks for the pointers, I will try incorporating this

**Pull request closed without merging**
